#!/bin/bash

ENV_FILE='.env.git.local'

echo "  ➜  Regenerating local environment file based on git info $ENV_FILE"
echo "# DO NOT EDIT THIS FILE IT IS AUTOMATICALLY GENERATED" > $ENV_FILE
echo "# this file is automatically generated by scripts/generate_git_env.sh" >> $ENV_FILE
echo "" >> $ENV_FILE

PROJECT_NAME=$(basename $(git remote get-url origin) .git | tr '[:upper:]' '[:lower:]')
echo "VITE_PROJECT_NAME          = $PROJECT_NAME" >> $ENV_FILE

HASH=$(git rev-parse --short HEAD)
echo "VITE_GIT_HASH              = $HASH" >> $ENV_FILE

echo "VITE_GIT_REPO_NAME         = $PROJECT_NAME" >> $ENV_FILE

GITURL=$(git remote get-url origin);
if [[ $GITURL == git@* ]];
then
    OWNER=$(echo $GITURL | awk -F':' '{print $2}' | awk -F'/' '{print $1}' );
else
    OWNER=$(echo $GITURL | awk -F'/' '{print $4}');
fi
OWNER=$(echo $OWNER | tr '[:upper:]' '[:lower:]')
echo "VITE_GIT_OWNER             = ${OWNER}" >> $ENV_FILE

BRANCH=$(git rev-parse --abbrev-ref HEAD | tr '[:upper:]' '[:lower:]')
echo "VITE_GIT_BRANCH_NAME       = $BRANCH" >> $ENV_FILE

echo "VITE_DEPLOY_BASE_PATH      = /${OWNER}/${PROJECT_NAME}/${BRANCH}/" >> $ENV_FILE

CODENAME=$(node scripts/codenamize.cjs "/${OWNER}/${PROJECT_NAME}/${BRANCH}")
echo "VITE_CODE_NAME             = ${CODENAME}" >> $ENV_FILE

escape_quotes() {
  input="$1"
  input="${input//\'/\'}"
  input="${input//\"/\\\"}"
  echo "$input"
}
MSG=$(escape_quotes "$(git log -1 --pretty=%s)");
echo "VITE_GIT_LAST_MSG          = $MSG" >> $ENV_FILE

echo "VITE_PROJECT_REF           = ${OWNER}-${PROJECT_NAME}-${BRANCH}" >> $ENV_FILE
