// AUTO-GENERATED by scripts/bundle-migrations.js — do not edit by hand.
// Run `pnpm db:generate` to regenerate after schema changes.

export interface BundledMigration {
  tag: string
  when: number
  sql: string
}

export const MIGRATIONS: BundledMigration[] = [
  {
    "tag": "0000_right_lyja",
    "when": 1780177928624,
    "sql": "CREATE TABLE `dev_sessions` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`expires_at` integer NOT NULL\n);\n--> statement-breakpoint\nCREATE TABLE `participants` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`project_id` text NOT NULL,\n\t`data` text NOT NULL,\n\t`created_at` integer NOT NULL,\n\t`updated_at` integer NOT NULL,\n\tFOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON UPDATE no action ON DELETE no action\n);\n--> statement-breakpoint\nCREATE TABLE `private_data` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`participant_id` text NOT NULL,\n\t`data` text NOT NULL,\n\t`created_at` integer NOT NULL,\n\t`updated_at` integer NOT NULL,\n\tFOREIGN KEY (`participant_id`) REFERENCES `participants`(`id`) ON UPDATE no action ON DELETE no action\n);\n--> statement-breakpoint\nCREATE TABLE `projects` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`owner` text NOT NULL,\n\t`repo` text NOT NULL,\n\t`branch` text NOT NULL,\n\t`mode` text DEFAULT 'live' NOT NULL,\n\t`created_at` integer NOT NULL\n);\n"
  }
]
