#!/bin/bash

ENV_FILE='.env.git.local'

echo "  ➜  Regenerating local environment file based on git info $ENV_FILE"
echo "# DO NOT EDIT THIS FILE IT IS AUTOMATICALLY GENERATED" > $ENV_FILE
echo "# this file is automatically generated by scripts/generate_git_env.sh" >> $ENV_FILE
echo ""  >> $ENV_FILE

# Project name from git remote, or fall back to directory name
PROJECT_NAME=$(basename "$(git remote get-url origin 2>/dev/null)" .git 2>/dev/null | tr '[:upper:]' '[:lower:]')
if [ -z "$PROJECT_NAME" ]; then
  PROJECT_NAME=$(basename "$(pwd)" | tr '[:upper:]' '[:lower:]')
fi
echo "VITE_PROJECT_NAME          = $PROJECT_NAME" >> $ENV_FILE

# Git hash, or placeholder
HASH=$(git rev-parse --short HEAD 2>/dev/null || echo "0000000")
echo "VITE_GIT_HASH              = $HASH" >> $ENV_FILE

echo "VITE_GIT_REPO_NAME         = $PROJECT_NAME" >> $ENV_FILE

# Owner from git remote URL
OWNER=""
GITURL=$(git remote get-url origin 2>/dev/null)
if [ -n "$GITURL" ]; then
  if [[ $GITURL == git@* ]]; then
    OWNER=$(echo "$GITURL" | awk -F':' '{print $2}' | awk -F'/' '{print $1}')
  else
    OWNER=$(echo "$GITURL" | awk -F'/' '{print $4}')
  fi
fi
OWNER=$(echo "${OWNER:-local}" | tr '[:upper:]' '[:lower:]')
echo "VITE_GIT_OWNER             = ${OWNER}" >> $ENV_FILE

# Branch name
BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "main")
BRANCH=$(echo "$BRANCH" | tr '[:upper:]' '[:lower:]')
echo "VITE_GIT_BRANCH_NAME       = $BRANCH" >> $ENV_FILE

echo "VITE_DEPLOY_BASE_PATH      = /${OWNER}/${PROJECT_NAME}/${BRANCH}/" >> $ENV_FILE

# Codename (optional — skip if codenamize not available)
CODENAME=$(node scripts/codenamize.cjs "/${OWNER}/${PROJECT_NAME}/${BRANCH}" 2>/dev/null || echo "unnamed-experiment")
echo "VITE_CODE_NAME             = ${CODENAME}" >> $ENV_FILE

escape_quotes() {
  input="$1"
  input="${input//\'/\'}"
  input="${input//\"/\\\"}"
  echo "$input"
}
MSG=$(escape_quotes "$(git log -1 --pretty=%s 2>/dev/null || echo '(no commits yet)')")
echo "VITE_GIT_LAST_MSG          = $MSG" >> $ENV_FILE

echo "VITE_PROJECT_REF           = ${OWNER}-${PROJECT_NAME}-${BRANCH}" >> $ENV_FILE
